### PR TITLE
Various grammar fixes and rewrites from the start until Software Spec…

### PR DESCRIPTION
**Pull request by Jameskr97**
…ification

### CODE REVIEW

**Comment by tuhdo** [comment]
Hello,

Thanks for the PR. Could you rebase against latest master, and use Lyx 2.1 for compatibility? I'm sorry for the inconvenience.

**Comment by Jameskr97** [comment]
Specifically 2.1? I'm using 2.2.2 downloaded from [here](https://www.lyx.org/Download).

**Comment by tuhdo** [comment]
It's unfortunate. Maybe you can consider this workaround:

- Copy your content into a plain text file
- Copy old content into a plain text file.
- Make a diff between the 2.
- Paste the diff here.

I will fix it in the book and mention you in the commit.

**Comment by Jameskr97** [comment]
What if instead I extract what I changed, and after it gets moved to a non-binary format, I can make a pull request then? It might take me a little while to complete a git-diff and find exactly what I changed.

**Comment by tuhdo** [comment]
Lyx allows exporting to `.txt ` format. I will add the `.txt` file, and you can make changes there. Then, I integrate the change into the Lyx file manually. Does it sound ok to you?

**Comment by Jameskr97** [comment]
Ok. Let's do that.

**Comment by tuhdo** [comment]
I added the `.txt` file.

**Pull request closed without merging**
